const CALENDAR_NUMBER_CHANGE_ANIMATION_TIME = 300;
const MODAL_ANIMATION_TIME = 500;
const INPUT_DROPDOWN_ANIMATION_TIME = 500;
const HEADER_TEXT = '우아한 가계부';
const PAYMENT_MODAL_TITLE = '추가하실 결제수단을 적어주세요.';
const PAYMENT_MODAL_CANCEL_TEXT = '취소';
const PAYMENT_MODAL_SUBMIT_TEXT = '등록';
const PAYMENT_MODAL_PLACEHOLDER = '입력하세요';

export {
  CALENDAR_NUMBER_CHANGE_ANIMATION_TIME,
  INPUT_DROPDOWN_ANIMATION_TIME,
  MODAL_ANIMATION_TIME,
  HEADER_TEXT,
  PAYMENT_MODAL_TITLE,
  PAYMENT_MODAL_CANCEL_TEXT,
  PAYMENT_MODAL_SUBMIT_TEXT,
  PAYMENT_MODAL_PLACEHOLDER,
};
