const CALENDAR_NUMBER_CHANGE_ANIMATION_TIME = 300;
const MODAL_ANIMATION_TIME = 500;
const INPUT_DROPDOWN_ANIMATION_TIME = 500;
const HEADER_TEXT = '우아한 가계부';
const PAYMENT_MODAL_TITLE = '추가하실 결제수단을 적어주세요.';
const PAYMENT_MODAL_CANCEL_TEXT = '취소';
const PAYMENT_MODAL_SUBMIT_TEXT = '등록';
const PAYMENT_MODAL_PLACEHOLDER = '입력하세요';

const LINE_CHART = {
  CURVE_RATIO: 0.4,
  MIN_CURVE_VALUE: 40,
  MAX_VALUE_RATIO: 1.2,
  POINT_WAIT_TIME: 0.9,
  POINT_WAIT_INTERVAL: 0.2,
  WIDTH: 600,
  HEIGHT: 300,
  INTERVAL: 50,
};

export {
  CALENDAR_NUMBER_CHANGE_ANIMATION_TIME,
  INPUT_DROPDOWN_ANIMATION_TIME,
  MODAL_ANIMATION_TIME,
  HEADER_TEXT,
  PAYMENT_MODAL_TITLE,
  PAYMENT_MODAL_CANCEL_TEXT,
  PAYMENT_MODAL_SUBMIT_TEXT,
  PAYMENT_MODAL_PLACEHOLDER,
  LINE_CHART,
};
