const CALENDAR_NUMBER_CHANGE_ANIMATION_TIME = 300;
const MODAL_ANIMATION_TIME = 500;
const INPUT_DROPDOWN_ANIMATION_TIME = 300;
const HEADER_TEXT = '우아한 가계부';
const PAYMENT_MODAL_TITLE = '추가하실 결제수단을 적어주세요.';
const PAYMENT_MODAL_CANCEL_TEXT = '취소';
const PAYMENT_MODAL_SUBMIT_TEXT = '등록';
const PAYMENT_MODAL_PLACEHOLDER = '입력하세요';
const PIE_CHART_TRANSITION_WAIT = 300;
const PIE_CHART_TRANSITION_DURATION = 2000;

const COLOR_CONSTANT = {
  CATEGORY_1: '#6ED5EB',
  CATEGORY_2: '#4CB8B8',
  CATEGORY_3: '#94D3CC',
  CATEGORY_4: '#4CA1DE',
  CATEGORY_5: '#D092E2',
  CATEGORY_6: '#817DCE',
  CATEGORY_7: '#4A6CC3',
  CATEGORY_8: '#B9D58C',
  CATEGORY_9: '#E6D267',
  CATEGORY_10: '#E2B765',
};

const LINE_CHART = {
  CURVE_RATIO: 0.4,
  MIN_CURVE_VALUE: 40,
  MAX_VALUE_RATIO: 1.2,
  POINT_WAIT_TIME: 0.9,
  POINT_WAIT_INTERVAL: 0.2,
  WIDTH: 600,
  HEIGHT: 300,
  INTERVAL: 50,
};

export {
  CALENDAR_NUMBER_CHANGE_ANIMATION_TIME,
  INPUT_DROPDOWN_ANIMATION_TIME,
  MODAL_ANIMATION_TIME,
  HEADER_TEXT,
  PAYMENT_MODAL_TITLE,
  PAYMENT_MODAL_CANCEL_TEXT,
  PAYMENT_MODAL_SUBMIT_TEXT,
  PAYMENT_MODAL_PLACEHOLDER,
  COLOR_CONSTANT,
  PIE_CHART_TRANSITION_WAIT,
  PIE_CHART_TRANSITION_DURATION,
  LINE_CHART,
};
